/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package tarea3;

import org.junit.Test;
import static org.junit.Assert.*;

public class AppTest {
    @Test public void testAppHasAGreeting() {
        Hospital classUnderTest = new Hospital();
        assertNotNull("app should have a greeting", classUnderTest.getGreeting());
    }
}
